### ISSUE TITLE
Update supplier info for J2, J3, J4 to Farnell

### ISSUE THREAD

**Issue by robertferanec** [hemalchevli/openrex-hdd-add-on#1]
I could not buy J2, J3, J4  from Digkikey (components are not in stock), however I was able to buy them from Farnell. Please update the components in schematic with new supplier, so we do not need to search where to buy the components in future.

J2: Change to 2056081:
http://sk.farnell.com/samtec/tsm-120-01-t-dv/header-2-54mm-smt-40way/dp/2056081 

J3 & J4: Change to 1803258
http://sk.farnell.com/samtec/ftr-102-01-s-s/header-1-27-x-2-54mm-smd-1x2way/dp/1803258

**Comment by hemalchevli** [comment]
I've updated the components as requested.
Thank you.
