### ISSUE TITLE
Add mating connector info

### ISSUE THREAD

**Issue by robertferanec** [hemalchevli/openrex-hdd-add-on#2]
Please add into schematic a note about mating connector for J3 and J4, so we do not need to search for it in future. The mating connector should be:
http://sk.farnell.com/samtec/sms-102-01-g-s/socket-1-27-x-2-54mm-1x2way/dp/1803251

**Comment by hemalchevli** [comment]
I've added a design note with manufacture and supplier part number for future reference of J3 and J4.
Thank you.
