### ISSUE TITLE
Connect all OpenRex J1 and J2 connector ground pins to GND net

### ISSUE THREAD

**Issue by robertferanec** [hemalchevli/openrex-hdd-add-on#3]
For better return path, it may be good to connect all GND pins of J1 and J2 connectors to GND. (Especially the pin 16 of J1, which is close to the SATA connector may be, important for SATA interface.)

**Comment by hemalchevli** [comment]
Yes, that is a good idea, sorry for the late reply, my email notifications were turn off.
I'll make the required changes and also add the decoupling capacitors.
